version: '3.6'

services:

  # Elasticsearch. See README for necessary host settings.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data_vol:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Postgres/PostGIS
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file:
      - api/config/db/db_env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data

  # Memcached for Django
  memcached:
      image: memcached:${MEMCACHED_VERSION}

  # Radiam API
  radiamapi:
    container_name: radiamapi
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["/wait-for-it/wait-for-it.sh", "db:5432", "-s", "--timeout=60", "--", "gunicorn", "--bind", ":8000", "--reload", "radiam.wsgi:application"]
    environment:
      - SESSIONAUTH=1
    volumes:
      - ./api:/code
      - static_volume:/django/static
    healthcheck:
      test: "curl -X OPTIONS http://localhost:8000 -H 'Origin: http://localhost:8000' -H 'Access-Control-Request-Headers: Origin, Accept, Content-Type' -H 'Access-Control-Request-Method: GET' || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - elasticsearch
      - migration
      - memcached
      - db

  # Run database migrations for Django on startup.
  migration:
    build:
      context: . 
      dockerfile: Dockerfile.api
    command: ["/wait-for-it/wait-for-it.sh", "db:5432", "-s", "--timeout=60", "--", "python", "/code/manage.py", "migrate", "--noinput"]
    volumes:
      - ./api:/code
    restart: on-failure
    depends_on:
      - db

  # Run Radiam Initialization after the application is built
  init:
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: ["/wait-for-it/wait-for-it.sh", "elasticsearch:9200", "-s", "--timeout=60", "--", "python", "/code/manage.py", "radiam"]
    volumes:
      - ./api:/code
    depends_on:
      - elasticsearch

  # Radiam GUI
  radiamgui:
    container_name: radiamgui
    build:
      context: .
      dockerfile: Dockerfile.gui
    healthcheck:
      test: "curl -X OPTIONS http://localhost:3000 -H 'Origin: http://localhost:3000' -H 'Access-Control-Request-Headers: Origin, Accept, Content-Type' -H 'Access-Control-Request-Method: GET' || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - './gui:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  # Web server for both the GUI and API
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "8100:80"
    volumes:
      - ./api/config/nginx/conf.d/local/:/etc/nginx/conf.d
      - ./api/uploads/:/django/uploads
      - static_volume:/django/static
    depends_on:
      - radiamapi
      - radiamgui

  osfconnector:
    build:
      context: .
      dockerfile: ./api/Dockerfile.radiam-osf
    command: ["/wait-for-it/wait-for-it.sh", "nginx:80", "-s", "--timeout=60", "--", "python", "osf_connector.py"]
    depends_on:
      - nginx

volumes:
      elasticsearch_data_vol:
      postgres_data_vol:
      static_volume:
