from .userpermissionstests import *
from .projectpermissionstests import *
from .researchgrouppermissionstests import *
from .groupmemberpermissionstests import *
from .groupviewgrantpermissionstests import *
from .grouphierarchytests import *
from .datasetdatacollectionmethodpermissionstests import *
from .datasetsensitivitypermissionstests import *
from .projectstatisticspermissiontests import *
