# Generated by Django 2.2.3 on 2019-07-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190725_2131'),
        ('api', '0004_geodata'),
    ]

    operations = [
    ]
