# Generated by Django 2.2.3 on 2019-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20190726_1521'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useragentprojectconfig',
            constraint=models.UniqueConstraint(fields=('agent', 'project'), name='unique_agent_project_configuration'),
        ),
    ]
