# Generated by Django 2.2.5 on 2019-09-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190731_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='osf_project',
            field=models.TextField(blank=True, help_text='If this location is of type OSF then project is required.', null=True),
        ),
        migrations.AddField(
            model_name='useragent',
            name='crawl_minutes',
            field=models.IntegerField(blank=True, default=15, help_text='How many minutes between crawling (for remote API agents)'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user agent is active'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='remote_api_token',
            field=models.CharField(blank=True, help_text='The remote API token (if applicable)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useragent',
            name='remote_api_username',
            field=models.CharField(blank=True, help_text='The remote API username (if applicable)', max_length=120, null=True),
        ),
        migrations.RunSQL("INSERT INTO rdm_location_types (id, label) VALUES ('6ebfd637-c40b-4486-9cf5-b0b976f51de5', 'location.type.osf');"),
    ]
