# Generated by Django 2.2.6 on 2019-10-17 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_datacite_4_2_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='local_access_token',
            field=models.CharField(blank=True, help_text='JWT access token for local API', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useragent',
            name='local_refresh_token',
            field=models.CharField(blank=True, help_text='JWT refresh token for local API', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choicelist',
            name='label',
            field=models.CharField(blank=True, help_text='A label identifying the contents of this list', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='choicelistvalue',
            name='label',
            field=models.CharField(blank=True, help_text='A label identifying the contents of this list', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='choicelistvalue',
            name='list',
            field=models.ForeignKey(help_text='The list of this value', on_delete=django.db.models.deletion.PROTECT, to='api.ChoiceList'),
        ),
        migrations.AlterField(
            model_name='choicelistvalue',
            name='value',
            field=models.CharField(help_text='The value to store for the metadata field if this choice is picked', max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='The dataset represented by this entity', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Dataset'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='The file represented by this entity', null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='folder',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='The folder represented by this entity', null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group represented by this entity', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ResearchGroup'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project represented by this entity', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Project'),
        ),
        migrations.AlterField(
            model_name='field',
            name='choice_list',
            field=models.ForeignKey(blank=True, help_text='A list of choices and values that cover the options for this metadata field.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ChoiceList'),
        ),
        migrations.AlterField(
            model_name='field',
            name='default_order',
            field=models.IntegerField(default=-1, help_text='The default order to display the field in the UI'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.CharField(blank=True, help_text='A label identifying the schema', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent field of this metadata field', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Field'),
        ),
        migrations.AlterField(
            model_name='metadatauitype',
            name='key',
            field=models.CharField(help_text='A key that maps to an xml element', max_length=80),
        ),
        migrations.AlterField(
            model_name='metadatauitype',
            name='label',
            field=models.CharField(help_text='A label identifying the type of UI input to use for this field', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatavaluetype',
            name='key',
            field=models.CharField(help_text='A key that maps to an xml element', max_length=80),
        ),
        migrations.AlterField(
            model_name='metadatavaluetype',
            name='label',
            field=models.CharField(help_text='A label identifying the type of value to store for this field', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='label',
            field=models.CharField(blank=True, help_text='A label identifying the schema', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='selectedfield',
            name='entity',
            field=models.ForeignKey(help_text='The entity that has selected this field', on_delete=django.db.models.deletion.PROTECT, to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='selectedfield',
            name='field',
            field=models.ForeignKey(help_text='The field chosen by this entity', on_delete=django.db.models.deletion.PROTECT, to='api.Field'),
        ),
        migrations.AlterField(
            model_name='selectedfield',
            name='required',
            field=models.BooleanField(default=False, help_text='Whether this metadata field is required'),
        ),
        migrations.AlterField(
            model_name='selectedfield',
            name='visible',
            field=models.BooleanField(default=False, help_text='Whether this metadata field should be shown in the UI'),
        ),
        migrations.AlterField(
            model_name='selectedschema',
            name='entity',
            field=models.ForeignKey(help_text='The entity that has selected this schema', on_delete=django.db.models.deletion.PROTECT, to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='selectedschema',
            name='schema',
            field=models.ForeignKey(help_text='The schema chosen by this entity', on_delete=django.db.models.deletion.PROTECT, to='api.Schema'),
        ),
    ]
