# Generated by Django 2.2.6 on 2019-10-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191017_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='local_access_token',
            field=models.CharField(blank=True, help_text='JWT access token for local API', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='local_refresh_token',
            field=models.CharField(blank=True, help_text='JWT refresh token for local API', max_length=2000, null=True),
        ),
    ]
