# Generated by Django 2.2.6 on 2019-11-07 05:24

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191018_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames must be between 3 and 12 characters long, alphanumeric, and contain no upper case characters', regex='^[a-z0-9]{3,12}$')]),
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dataset', models.ForeignKey(help_text='The dataset associated with this search', on_delete=django.db.models.deletion.PROTECT, to='api.Dataset')),
            ],
            options={
                'db_table': 'rdm_searches',
            },
        ),
    ]
