# Generated by Django 2.2.6 on 2019-11-12 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191018_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprole',
            name='label',
            field=models.CharField(help_text='The label for this role', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames must be between 3 and 12 characters long, alphanumeric, and contain no upper case characters', regex='^[a-z0-9]{3,12}$')]),
        ),
    ]
