# Generated by Django 2.2.6 on 2019-11-13 05:24

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191112_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dataset', models.ForeignKey(help_text='The dataset associated with this search', unique=True, on_delete=django.db.models.deletion.PROTECT, to='api.Dataset')),
            ],
            options={
                'db_table': 'rdm_searches',
            },
        ),
    ]
