# Generated by Django 2.2.6 on 2019-11-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191113_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='dataset',
            field=models.OneToOneField(help_text='The dataset associated with this search', on_delete=django.db.models.deletion.PROTECT, to='api.Dataset'),
        ),
    ]
