# Generated by Django 2.2 on 2020-02-04 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191114_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.ForeignKey(help_text='The location this project applies to', on_delete=django.db.models.deletion.PROTECT, to='api.Location')),
                ('project', models.ForeignKey(help_text='The project', on_delete=django.db.models.deletion.PROTECT, to='api.Project')),
            ],
            options={
                'db_table': 'rdm_location_projects',
            },
        ),
    ]
