from .usertests import *
from .researchgroupstests import *
from .groupmembertests import *
from .grouproletests import *
from .datasettests import *
from .projecttests import *
from .searchtests import *
from .documenttests import *
from .filtertests import *
from .locationtests import *
from .permissionstests import *
from .sortingtests import *
from .useragenttests import *
from .geodatatests import *
from .permissionsunittests import *
from .servicestests import *
from .search import *
